export const dynamic = 'force-dynamic';

import React from 'react';
import { Metadata } from 'next';
import styles from './page.module.css';
import { api } from '@/lib/api/api.server';

export const metadata: Metadata = {
  title: "scaf-next - dashboard",
  description: "Generated by create next app",
};

const DashboardPage: React.FC = async () => {
  const data: any = await api.get('accounts/me');
  return (
    <div className={styles.container}>
      ようこそ {data.account_name} さん
    </div>
  );
};

export default DashboardPage;