import React from 'react';
import type { Metadata } from "next";
import styles from './page.module.css';
import Header from '@/components/layout/header';
import Main from '@/components/layout/main';
import Footer from "@/components/layout/footer";
import SignupLink from '@/components/parts/button/signup-link';
import LoginForm from './login-form';

export const metadata: Metadata = {
  title: "scaf-next - login",
  description: "Generated by create next app",
};

const LoginPage: React.FC = () => {
  return (
    <>
      <Header>
        <SignupLink />
      </Header>
      <Main>
        <div className={styles.container}>
          <LoginForm />
        </div>
      </Main>
      <Footer />
    </>
  );
};

export default LoginPage;
