import React from 'react';
import type { Metadata } from "next";
import styles from './page.module.css';
import Header from '@/components/layout/header';
import Main from '@/components/layout/main';
import Footer from "@/components/layout/footer";
import LoginLink from '../components/parts/button/login-link';
import SignupForm from './signup-form';

export const metadata: Metadata = {
  title: "scaf-next - signup",
  description: "Generated by create next app",
};

const SignupPage: React.FC = () => {
  return (
    <>
      <Header>
        <LoginLink />
      </Header>
      <Main>
        <div className={styles.container}>
          <SignupForm />
        </div>
      </Main>
      <Footer />
    </>
  );
};

export default SignupPage;
